export const UPDATE_CELL_WIDTH = "UPDATE_CELL_WIDTH";
export type UPDATE_CELL_WIDTH = typeof UPDATE_CELL_WIDTH;

export const UPDATE_ROW_HEIGHT = "UPDATE_ROW_HEIGHT";
export type UPDATE_ROW_HEIGHT = typeof UPDATE_ROW_HEIGHT;

export const UPDATE_HIDDEN_COLUMNS_INDEXTES = "UPDATE_HIDDEN_COLUMNS_INDEXTES";
export type UPDATE_HIDDEN_COLUMNS_INDEXTES = typeof UPDATE_HIDDEN_COLUMNS_INDEXTES;

export const UPDATE_COLUMNS_CURSOR = "UPDATE_COLUMNS_CURSOR";
export type UPDATE_COLUMNS_CURSOR = typeof UPDATE_COLUMNS_CURSOR;
